### ISSUE TITLE
Question: Make `GeneratesSnsMessages` a public trait?

### ISSUE THREAD

**Issue by stefanzweifel** [renoki-co/laravel-aws-webhooks#12]
Hi there 👋 

First, thanks for building such a lovely package. It saves me so much time when adding SES/SNS to new apps.

I'm currently adding the package to an app, where I would like to test my webhook handle methods. I've seen that you have a [`GeneratesSnsMessages`-trait](https://github.com/renoki-co/laravel-aws-webhooks/blob/8f5e7490a86b2a2419cb59925e884a1244d9e80b/tests/Concerns/GeneratesSnsMessages.php) for your own tests to quickly generate the payload.

I've now copy/pasted the trait into my own app to make testing easier. Works great! My tests are straightforward and easy to read.

```php
/** @test */
public function it_logs_aws_sns_ses_webhook_event_for_complaint_event_and_updates_timestamp()
{
    $send = Send::factory()->create();

    $payload = $this->getNotificationPayload([
        'eventType' => 'Complaint',
        'mail' => [
            'messageId' => $send->transport_message_id,
        ],
    ]);

    $response = $this->makeHttpRequestToController($payload);

    $response->assertOk();

    $this->assertNotNull($send->refresh()->complained_at);
}
```

Would you be open for a PR, which would move the `GeneratesSnsMessages`-trait to the `src`-folder?
As the `test`-folder is only autoloaded in development, I can't use your `GeneratesSnsMessages`-trait directly as a package consumer.

I also had to overwrite the `getMessageValidator`-message in my Controller (like [in your tests](https://github.com/renoki-co/laravel-aws-webhooks/blob/master/tests/Controllers/SesController.php#L11-L22)).
Maybe this could also be solved with a `app()->environment('testing')` if-condition?

**Comment by rennokki** [comment]
It was placed under the test folder because it is used for development only, as it shouldn't be used in production packages. Usually when you `composer install package`, the dev autoload still loads it since it wasnt installed with `--no-dev`

Do you need this in production, like when running `composer install --no-dev`?

**Comment by stefanzweifel** [comment]
> Do you need this in production, like when running composer install --no-dev?

No, we don't need this in production. I'm using the copy of the `GeneratesSnsMessages`-trait in the apps test suite. Tests are not run in production. Only on local machines and in the CI environment.

Locally I don't use `composer install --no-dev`, as I want  my dev-dependencies installed. Theoretically `composer install` (without `--no-dev`) should add the dev paths of dependencies to the autoloader. But this doesn't seem to work on my machine with the latest composer version. A subsequent `composer dump-autoload` doesn't help either. 🤔 

```
PHP Fatal error:  Trait 'Rennokki\LaravelSnsEvents\Tests\Concerns\GeneratesSnsMessages' 
not found in /tests/Features/AwsSnsSesWebhookControllerTest.php on line 11
```

I thought it would be great, if the package could also provide some sort of helper, to make testing ones own Controller easier. But I also totally understand the point of not wanting to add "dev only" code to the published package.
My copy of the trait works fine for me. ☺️

**Comment by rennokki** [comment]
I don't see any problem with a PR for this 😁

**Comment by stefanzweifel** [comment]
Thanks for the merge and release!
