### ISSUE TITLE
[Enhancement] Require specific (laravel) packages instead of laravel/framework

### ISSUE THREAD

**Issue by chancezeus** [renoki-co/laravel-aws-webhooks#5]
Currently this package requires ```laravel/framework``` as a dependency, this makes it import the entire Laravel Framework and thus makes it impossible to use the package in (for example) Lumen or in a custom project that leverages only some of the Laravel components.

I wonder if it would be possible to make the package depend on the specific ```illuminate/...``` packages instead, a quick source search shows me the following packages are used:
```
illuminate/http
illuminate/support
```

The same would apply to the ```rennokki/laravel-sns-events``` package, here the dependency list could be reduced to:
```
illuminate/http
illuminate/routing
illuminate/support
```

For development/testing purposes the ```orchestra/testbench``` package will in turn require the ```illuminate/framework```, thus making it available/usable during dev and testing without having to require it as a regular dependency.

**Comment by rennokki** [comment]
Thanks for the PRs! 🎉
